### PR TITLE
fix(settings): Restore original config when switching to Custom Platform

### LINKED ISSUE #146: [BUG]: Switching to Custom Platform retains modelId from previous platform
### 🐛 Bug description [Please make everyone to understand it]

In the settings page, when switching from Doubao or OpenAI platform to Custom Platform, the modelId field incorrectly retains the preset value from the previous platform instead of displaying the custom configuration information fetched from the backend.

### 🧑‍💻 Step to reproduce

1. Open the settings page
2. Select Doubao platform (modelId will be automatically set to "doubao-seed-1-6-flash-250828")
3. Switch to Custom Platform
4. Observe that the modelId field still shows "doubao-seed-1-6-flash-250828" instead of the custom configuration fetched from the backend

### 👾 Expected result

Regardless of which platform you switch from to Custom Platform, it should display the custom configuration information fetched from the backend, including the correct modelId, baseUrl, and other fields.

### 🚑 Any additional information

_No response_

### 🛠️ MineContext Version

V0.1.2

### 💻 Platform Details

Windows11

### PR DESCRIPTION
**Pull request by AQIU20**
fix(settings): Restore original config when switching to Custom Platform

Description :
This PR fixes a bug where switching to Custom Platform retains the modelId from the previous platform instead of displaying the custom configuration fetched from the backend.

Changes :

- Added originalConfig state to store the original configuration fetched from the backend
- Modified the useMemo hook to not set modelId when on Custom Platform, preserving the original value
- Added useEffect to monitor platform switches and restore original configuration when switching to Custom Platform
- Updated getInfo function to save the original configuration fetched from the backend
Testing :

- Verified that switching from Doubao to Custom Platform now correctly displays the custom configuration
- Verified that switching from OpenAI to Custom Platform now correctly displays the custom configuration
- Confirmed that switching between Doubao and OpenAI still works as expected
Issue :
Fixes #146

### CODE REVIEW

File: frontend/src/renderer/src/pages/settings/settings.tsx [hunk 1]
```diff
@@ -139,12 +141,28 @@ const Settings: FC<Props> = (props: Props) => {
     return foundItem ? foundItem.option : []
   }, [modelPlatform])
 
+  // recover originalConfig when switch to custom
+  useEffect(() => {
+    if (isCustom && originalConfig) {
+      form.setFieldsValue({
```
Comment (pandaCure) [inline frontend/src/renderer/src/pages/settings/settings.tsx]: form.setFieldsValue(originalConfig)

File: frontend/src/renderer/src/pages/settings/settings.tsx [hunk 2]
```diff
@@ -120,6 +120,8 @@ const Settings: FC<Props> = (props: Props) => {
   const [errorMessage, setErrorMessage] = useState<string | null>(null)
   const [successMessage, setSuccessMessage] = useState<string | null>(null)
   const [isLoading, setIsLoading] = useState(false)
+  // originalConfig from backend  
+  const [originalConfig, setOriginalConfig] = useState<any>(null)
```
Comment (pandaCure) [inline frontend/src/renderer/src/pages/settings/settings.tsx]: Replace the 'any' type with a specific type
